name: Daily YouTube Trend Collection

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  collect_trends:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to YouTube API collector
      run: |
        curl -X POST "https://workflows-1.onrender.com/api/trends/youtube" \
        -H "Content-Type: application/json"
